apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-crd
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-crd
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-configs
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-configs
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector-crd
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector-crd
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kube-prometheus-stack
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring-dashboards
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring-dashboards
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging-crd
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-logging-crd
  targets:
  - name: logging
    clusterSelector:
      matchLabels:
        logging: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-logging
  targets:
  - name: logging
    clusterSelector:
      matchLabels:
        logging: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/cert-manager
  targets:
  - name: cert-manager
    clusterSelector:
      matchLabels:
        cert-manager: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden-crds
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden-crds
  targets:
  - name: kubewarden-crds
    clusterSelector:
      matchLabels:
        kubewarden: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden
  targets:
  - name: kubewarden
    clusterSelector:
      matchLabels:
        kubewarden: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden-defaults
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden-defaults
  targets:
  - name: kubewarden-defaults
    clusterSelector:
      matchLabels:
        kubewarden: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: compliance-crd
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-compliance-crd
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: compliance
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-compliance
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: stig-profiles
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/rgs-stig-profiles
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ai-gpu-operator
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/gpu-operator
  targets:
  - name: ai
    clusterSelector:
      matchLabels:
        ai: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ai-cloudnative-pg
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/cloudnative-pg
  targets:
  - name: ai
    clusterSelector:
      matchLabels:
        ai: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ai-milvus
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/milvus
  targets:
  - name: ai
    clusterSelector:
      matchLabels:
        ai: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ai-ollama
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/ollama
  targets:
  - name: ai
    clusterSelector:
      matchLabels:
        ai: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ai-litellm
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/litellm
  targets:
  - name: ai
    clusterSelector:
      matchLabels:
        ai: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ai-open-webui
  namespace: fleet-default
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/open-webui
  targets:
  - name: ai
    clusterSelector:
      matchLabels:
        ai: enabled
