apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-crd
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-configs
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-configs
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector-crd
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kube-prometheus-stack
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kube-prometheus-stack
  targets:
  - name: kube-prometheus-stack
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-monitoring-dashboards
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring-dashboards
  targets:
  - name: kube-prometheus-stack
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-logging-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-logging-crd
  targets:
  - name: rancher-logging
    clusterSelector:
      matchLabels:
        logging: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-logging
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-logging
  targets:
  - name: rancher-logging
    clusterSelector:
      matchLabels:
        logging: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/cert-manager
  targets:
  - name: cert-manager
    clusterSelector:
      matchLabels:
        cert-manager: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: admission-controller
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/admission-controller
  targets:
  - name: admission-controller
    clusterSelector:
      matchLabels:
        admission-controller: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden
  targets:
  - name: kubewarden
    clusterSelector:
      matchLabels:
        kubewarden: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: vulnerability-scanner
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/vulnerability-scanner
  targets:
  - name: vulnerability-scanner
    clusterSelector:
      matchLabels:
        vulnerability-scanner: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: runtime-enforcer
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/runtime-enforcer
  targets:
  - name: runtime-enforcer
    clusterSelector:
      matchLabels:
        runtime-enforcer: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager-csi-driver
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/cert-manager-csi-driver
  targets:
  - name: cert-manager-csi-driver
    clusterSelector:
      matchLabels:
        cert-manager-csi-driver: enabled
  - name: runtime-enforcer
    clusterSelector:
      matchLabels:
        runtime-enforcer: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cloudnative-pg
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/cloudnative-pg
  targets:
  - name: cloudnative-pg
    clusterSelector:
      matchLabels:
        cloudnative-pg: enabled
  - name: vulnerability-scanner
    clusterSelector:
      matchLabels:
        vulnerability-scanner: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-compliance-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-compliance-crd
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-compliance
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-compliance
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rgs-stig-profiles
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/rgs-stig-profiles
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: airgapped-docs
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/airgapped-docs
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ui-plugin-catalog
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'oci://registry\.ranchercarbide\.dev(/|$)'
  paths:
    - /fleet/ui-plugin-catalog
  targets:
  - name: ui-plugin-catalog
    clusterSelector:
      matchLabels:
        ui-extensions: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: capa-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/capa-ui-extension
  targets:
  - name: capa-ui-extension
    clusterSelector:
      matchLabels:
        capa-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: elemental-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/elemental-ui-extension
  targets:
  - name: elemental-ui-extension
    clusterSelector:
      matchLabels:
        elemental-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: harvester-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/harvester-ui-extension
  targets:
  - name: harvester-ui-extension
    clusterSelector:
      matchLabels:
        harvester-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: admission-controller-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/admission-controller-ui-extension
  targets:
  - name: admission-controller-ui-extension
    clusterSelector:
      matchLabels:
        admission-controller-ui-extension: enabled
  - name: kubewarden-ui-extension
    clusterSelector:
      matchLabels:
        kubewarden-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector-ui-extension
  targets:
  - name: neuvector-ui-extension
    clusterSelector:
      matchLabels:
        neuvector-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: observability-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/observability-ui-extension
  targets:
  - name: observability-ui-extension
    clusterSelector:
      matchLabels:
        observability-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-ai-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-ai-ui-extension
  targets:
  - name: rancher-ai-ui-extension
    clusterSelector:
      matchLabels:
        rancher-ai-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: supportability-review-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/supportability-review-ui-extension
  targets:
  - name: supportability-review-ui-extension
    clusterSelector:
      matchLabels:
        supportability-review-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: virtual-clusters-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/virtual-clusters-ui-extension
  targets:
  - name: virtual-clusters-ui-extension
    clusterSelector:
      matchLabels:
        virtual-clusters-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: vulnerability-scanner-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/vulnerability-scanner-ui-extension
  targets:
  - name: vulnerability-scanner-ui-extension
    clusterSelector:
      matchLabels:
        vulnerability-scanner-ui-extension: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ai-cluster
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/ai-cluster
  targets:
  - name: ai
    clusterSelector:
      matchLabels:
        ai: enabled
---
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: carbide-charts
spec:
  gitBranch: main
  gitRepo: https://github.com/rancherfederal/carbide-charts
---
apiVersion: management.cattle.io/v3
customized: false
default: '{}'
kind: Setting
metadata:
  name: ui-banners
value: '{"loginError":{"message":"","showMessage":"false"},"bannerHeader":{"background":"#007a33","color":"#ffffff","textAlignment":"center","fontSize":"14px","text":"UNCLASSIFIED"},"bannerFooter":{"background":"#007a33","color":"#ffffff","textAlignment":"center","fontSize":"14px","text":"UNCLASSIFIED"},"bannerConsent":{"background":"#eeeff4","color":"#141419","button":"Accept","html":"<div
  style=\"font-size:24px;line-height:2.0;text-align:center;\">\n  <p style=\"margin:0
  0 12px 0;\"><strong>DoD Warning and Consent Banner</strong></p>\n</div>\n<div style=\"font-size:14px;line-height:1.6;text-align:center;\">\n  <p
  style=\"margin:0 0 12px 0;\"><strong>You are accessing a U.S. Government (USG) Information
  System (IS) that is provided for USG-authorized use only. By using this IS (which
  includes any device attached to this IS), you consent to the following conditions:</strong></p>\n  <p
  style=\"margin:0 0 12px 0;\">The USG routinely intercepts and monitors communications
  on this IS for purposes including, but not limited to, penetration testing, COMSEC
  monitoring, network operations and defense, personnel misconduct (PM), law enforcement
  (LE), and counterintelligence (CI) investigations.</p>\n  <p style=\"margin:0 0
  12px 0;\">At any time, the USG may inspect and seize data stored on this IS.</p>\n  <p
  style=\"margin:0 0 12px 0;\">Communications using, or data stored on, this IS are
  not private, are subject to routine monitoring, interception, and search, and may
  be disclosed or used for any USG authorized purpose.</p>\n  <p style=\"margin:0
  0 12px 0;\">This IS includes security measures (e.g., authentication and access
  controls) to protect USG interests--not for your personal benefit or privacy.</p>\n  <p
  style=\"margin:0 0 12px 0;\">Notwithstanding the above, using this IS does not constitute
  consent to PM, LE or CI investigative searching or monitoring of the content of
  privileged communications, or work product, related to personal representation or
  services by attorneys, psychotherapists, or clergy, and their assistants. Such communications
  and work product are private and confidential.</p>\n  <p style=\"margin:0 0 12px
  0;\">See User Agreement for details.</p>\n</div>"},"showHeader":"true","showFooter":"true","showConsent":"true"}'
