apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-crd
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-tests
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-tests
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector-crd
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring-crd
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
### Add Classification Banners
apiVersion: management.cattle.io/v3
customized: false
default: '{}'
kind: Setting
metadata:
  name: ui-banners
value: '{"loginError":{"message":"","showMessage":"false"},"bannerHeader":{"background":"#007a33","color":"#ffffff","textAlignment":"center","fontWeight":null,"fontStyle":null,"fontSize":"14px","textDecoration":null,"text":"UNCLASSIFIED//FOUO"},"bannerFooter":{"background":"#007a33","color":"#ffffff","textAlignment":"center","fontWeight":null,"fontStyle":null,"fontSize":"14px","textDecoration":null,"text":"UNCLASSIFIED//FOUO"},"bannerConsent":{"background":"#eeeff4","color":"#141419","textAlignment":"center","fontWeight":null,"fontStyle":null,"fontSize":"14px","textDecoration":null,"text":"You
  are accessing a U.S. Government (USG) Information System (IS) that is provided for
  USG-authorized use only.\\nBy using this IS (which includes any device attached
  to this IS), you consent to the following conditions: The USG routinely intercepts
  and monitors communications on this IS for purposes including, but not limited to,
  penetration testing, COMSEC monitoring, network operations and defense, personnel
  misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations.
  At any time, the USG may inspect and seize data stored on this IS. Communications
  using, or data stored on, this IS are not private, are subject to routine monitoring,
  interception, and search, and may be disclosed or used for any USG-authorized purpose.
  This IS includes security measures (e.g., authentication and access controls) to
  protect USG interests--not for your personal benefit or privacy. Notwithstanding
  the above, using this IS does not constitute consent to PM, LE or CI investigative
  searching or monitoring of the content of privileged communications, or work product,
  related to personal representation or services by attorneys, psychotherapists, or
  clergy, and their assistants. Such communications and work product are private and
  confidential.\\n See User Agreement for details.","button":"Accept"},"showHeader":"true","showFooter":"true","showConsent":"true"}'