apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-crd
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-configs
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-configs
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector-crd
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kube-prometheus-stack
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring-dashboards
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring-dashboards
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-logging-crd
  targets:
  - name: logging
    clusterSelector:
      matchLabels:
        logging: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-logging
  targets:
  - name: logging
    clusterSelector:
      matchLabels:
        logging: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/cert-manager
  targets:
  - name: cert-manager
    clusterSelector:
      matchLabels:
        cert-manager: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden-crds
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden-crds
  targets:
  - name: kubewarden-crds
    clusterSelector:
      matchLabels:
        kubewarden: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden
  targets:
  - name: kubewarden
    clusterSelector:
      matchLabels:
        kubewarden: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden-defaults
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden-defaults
  targets:
  - name: kubewarden-defaults
    clusterSelector:
      matchLabels:
        kubewarden: enabled
---
### Rancher Government Carbide
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: compliance-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-compliance-crd
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: compliance
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-compliance
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: stig-profiles
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  helmSecretName: registry-creds
  helmRepoURLRegex: 'registry\.ranchercarbide\.dev'
  paths:
    - /fleet/rgs-stig-profiles
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: airgapped-docs
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/airgapped-docs
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector-ui-extension
  targets:
  - name: neuvector-ui-extension
    clusterSelector:
      matchLabels:
        ui-extensions: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden-ui-extension
  targets:
  - name: kubewarden-ui-extension
    clusterSelector:
      matchLabels:
        ui-extensions: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: elemental-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/elemental-ui-extension
  targets:
  - name: elemental-ui-extension
    clusterSelector:
      matchLabels:
        ui-extensions: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: observability-ui-extension
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/observability-ui-extension
  targets:
  - name: observability-ui-extension
    clusterSelector:
      matchLabels:
        ui-extensions: enabled
---
### Add Rancher Extensions Chart Repo
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: rancher-extensions
spec:
  gitBranch: main
  gitRepo: https://github.com/rancher/ui-plugin-charts
---
### Add Rancher Partner Extensions Chart Repo
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: rancher-partner-extensions
spec:
  gitBranch: main
  gitRepo: https://github.com/rancher/partner-extensions
---
### Add Rancher Government Carbide Chart Repo
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: carbide-charts
spec:
  gitBranch: main
  gitRepo: https://github.com/rancherfederal/carbide-charts
---
### Add Classification Banners
apiVersion: management.cattle.io/v3
customized: false
default: '{}'
kind: Setting
metadata:
  name: ui-banners
value: '{"loginError":{"message":"","showMessage":"false"},"bannerHeader":{"background":"#007a33","color":"#ffffff","textAlignment":"center","fontSize":"14px","text":"UNCLASSIFIED"},"bannerFooter":{"background":"#007a33","color":"#ffffff","textAlignment":"center","fontSize":"14px","text":"UNCLASSIFIED"},"bannerConsent":{"background":"#eeeff4","color":"#141419","button":"Accept","html":"<div
  style=\"font-size:24px;line-height:2.0;text-align:center;\">\n  <p style=\"margin:0
  0 12px 0;\"><strong>DoD Warning and Consent Banner</strong></p>\n</div>\n<div style=\"font-size:14px;line-height:1.6;text-align:center;\">\n  <p
  style=\"margin:0 0 12px 0;\"><strong>You are accessing a U.S. Government (USG) Information
  System (IS) that is provided for USG-authorized use only. By using this IS (which
  includes any device attached to this IS), you consent to the following conditions:</strong></p>\n  <p
  style=\"margin:0 0 12px 0;\">The USG routinely intercepts and monitors communications
  on this IS for purposes including, but not limited to, penetration testing, COMSEC
  monitoring, network operations and defense, personnel misconduct (PM), law enforcement
  (LE), and counterintelligence (CI) investigations.</p>\n  <p style=\"margin:0 0
  12px 0;\">At any time, the USG may inspect and seize data stored on this IS.</p>\n  <p
  style=\"margin:0 0 12px 0;\">Communications using, or data stored on, this IS are
  not private, are subject to routine monitoring, interception, and search, and may
  be disclosed or used for any USG authorized purpose.</p>\n  <p style=\"margin:0
  0 12px 0;\">This IS includes security measures (e.g., authentication and access
  controls) to protect USG interests--not for your personal benefit or privacy.</p>\n  <p
  style=\"margin:0 0 12px 0;\">Notwithstanding the above, using this IS does not constitute
  consent to PM, LE or CI investigative searching or monitoring of the content of
  privileged communications, or work product, related to personal representation or
  services by attorneys, psychotherapists, or clergy, and their assistants. Such communications
  and work product are private and confidential.</p>\n  <p style=\"margin:0 0 12px
  0;\">See User Agreement for details.</p>\n</div>"},"showHeader":"true","showFooter":"true","showConsent":"true"}'
