apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-crd
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn-configs
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/longhorn-configs
  targets:
  - name: longhorn
    clusterSelector:
      matchLabels:
        longhorn: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector-crd
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: neuvector
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/neuvector
  targets:
  - name: neuvector
    clusterSelector:
      matchLabels:
        neuvector: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring-crd
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-monitoring
  targets:
  - name: monitoring
    clusterSelector:
      matchLabels:
        monitoring: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging-crd
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-logging-crd
  targets:
  - name: logging
    clusterSelector:
      matchLabels:
        logging: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: logging
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/rancher-logging
  targets:
  - name: logging
    clusterSelector:
      matchLabels:
        logging: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cert-manager
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/cert-manager
  targets:
  - name: cert-manager
    clusterSelector:
      matchLabels:
        cert-manager: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden-crds
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden-crds
  targets:
  - name: kubewarden-crds
    clusterSelector:
      matchLabels:
        kubewarden: enabled
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubewarden
  namespace: fleet-local
spec:
  repo: https://github.com/zackbradys/fleet
  branch: main
  paths:
    - /fleet/kubewarden
  targets:
  - name: kubewarden
    clusterSelector:
      matchLabels:
        kubewarden: enabled
