global:
  cattle:
    systemDefaultRegistry: registry.ranchercarbide.dev
auditScanner:
  policyReporter: true
policy-reporter:
  image:
    registry: registry.ranchercarbide.dev
  ui:
    image:
      registry: registry.ranchercarbide.dev
