controller:
  pvc:
    capacity: 10Gi
    enabled: true
  ranchersso:
    enabled: true
global:
  cattle:
    url: '${ if hasKey .ClusterLabels "server-url" }https://${ get .ClusterLabels "server-url" }${ end }'
k3s:
  enabled: true
manager:
  svc:
    type: ClusterIP
rbac: true
