controller:
  pvc:
    capacity: 10Gi
    enabled: true
  ranchersso:
    enabled: true
global:
  cattle:
    url: '${ if hasKey .ClusterLabels "server-url" }https://${ get .ClusterLabels "server-url" }${ end }'
k3s:
  enabled: true
manager:
  svc:
    type: ClusterIP
rbac: true
registry: registry.ranchercarbide.dev

enforcer:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - effect: NoSchedule
      key: node-role.kubernetes.io/etcd
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
