global:
  cattle:
    systemDefaultRegistry: registry.ranchercarbide.dev

persistence:
  defaultDataLocality: best-effort

defaultSettings:
  taintToleration: nvidia.com/gpu=true:NoSchedule
longhornManager:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
longhornDriver:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
